services:
  node:
    image: node:18.20.5
    container_name: sso-nest
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: bash -c "npm config set registry https://registry.npmmirror.com/ && npm i -g pnpm && npm run deploy"  # 安装依赖、构建和启动 NestJS 服务
    environment:
      - TZ=Asia/Shanghai
      - NODE_ENV=production 
      - MYSQL_HOST=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DB=sso
    depends_on:
      - mysql
    networks:
      - app-network
    ports:
      - "3000:3000"
    restart: on-failure

  mysql:
    image: mysql
    container_name: sso-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sso
    ports:
      - "3306:3306"
    volumes:
      - .cache:/var/lib/mysql
    networks:
      - app-network
    restart: on-failure

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
